### ISSUE TITLE
Schema fields don't work with PersistentList and Dict

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.schema#11]
In https://bugs.launchpad.net/zope.schema/+bug/131112, Damien Genet reported:

> `PersistentList` & `PersistentDict` aren't valid types for `List` & `Dict` schema fields. For instance the following code fails (where `IKLass` is a `zope.schema.List`) :

``` python
class Klass(Peristent):
    list = FieldProperty(IKlass['list'])

    def __init__(self):
        self.list = PersistentList ()
```

Damien attached a patch:  https://bugs.launchpad.net/zope.schema/+bug/131112/+attachment/128401/+files/_field.py.patch

@tseaver followed up:

> The intent of the patch looks reasonable, although it doesn't apply cleanly to the current zope.schema trunk. However, the patch needs to be extended with new tests showing the use of the new `PersistentList` / `PersistentDict` types.

**Comment by jamadden** [comment]
This package no longer has a dependency on `persistent`, so the original patch, which added `PersistentList` and `PersistentDict` to the `_type` attributes of `List` and `Dict` won't work (which are currently just `list` and `dict`, respectively).

What if those `_type` attributes were specified as `collections.MutableSequence` and `collections.MutableMapping`? `Persistent[List|Dict]` are instances of those classes, and users can register or create more.

The `IList` interface doesn't say that only a real, honest-to-goodness `list` object is acceptable, it says " a value that implements the API of a conventional Python list." `IDict` is a bit more restrictive, saying it holds "a conventional dict," but we could fudge that 😄

**Comment by jamadden** [comment]
Alternatively, we could add new fields and interfaces `MutableSequence` and `MutableMapping` that `Dict` and `List` could extend to tighten the contract.

I think I like that as it should avoid any chance of breaking existing code that really did want a `list` or `dict`. OTOH, if such code wanted to expand to accept any MutableSequence or Mapping, it would need a small change to opt-in; that's probably ok, because it probably needs to be tested with the expanded types anyway.
