### ISSUE TITLE
`zope.schema.Object._validate`: missing field information in error reports

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.schema#16]
In https://bugs.launchpad.net/zope.schema/+bug/620324, Dieter Maurer (dieter@handshake.de) reported:

> Error reports from `zope.schema.Object._validate` for field related errors often lack the information about the affected field. This makes identification of the affected fields unnecessarily difficult.
> 
> `dm.zope.schema.schema.Object._validate` provides a potential fix. It collects pairs fieldname, exception instead of exception alone in the `WrongContainedType` exception.

**Comment by jamadden** [comment]
I've run into this problem also and [implemented some workarounds](https://github.com/NextThought/nti.schema/blob/master/src/nti/schema/field.py#L170). I think it would be generally useful if WrongContainedType provided more information, preferably as attributes instead of just stuffed in `args[0]` (I realize that complicates pickling, but these things aren't usually pickled, right?)

- The field object doing the validation
- The value that failed validation
- A mapping of `{name in schema: exception}`

If we keep args[0] as the list of exceptions, this should be backwards compatible.
