### ISSUE TITLE
Missing python_requires

### ISSUE THREAD

**Issue by bertjwregeer** [zopefoundation/zope.schema#93]
Hey all,

This project is missing a `python_requires` which is causing build failures on Python 3.4 projects that accidentally install this, as `zope.interface` is correctly setup to use `python_requires`.

**Comment by mgedmin** [comment]
I don't think it's possible to fix this specifically for Python 3.4, because PyPI won't allow us to set python_requires metadata for old releases.  Either we delete old releases (which normally one should never do), or pip will find the latest release without python_requires metadata that you've already discovered no longer works on 3.4.

We can fix this going forward, so users of Python 3.5 won't be stranded when we drop 3.5 compatibility this September.

**Comment by bertjwregeer** [comment]
The other option is re-releasing an older version that works on Python 3.4 with a newer version number, then incrementing the newest version one more with a valid python_requires...

But that depends on how badly you consider the breakage for Python 3.4 users.

I found this due to a failing build of a downstream project... so either I go pin it for Python 3.4 or I drop python 3.4 support in what would otherwise still be a supported version of the software for Py3.4. I know Py3.4 is EOL...

**Comment by bertjwregeer** [comment]
Thanks for the addition either way!
